version: '2'
services:

    nginx:
        container_name: nginx
        image: "nginx:1.11.8-alpine"
        restart: unless-stopped
        ports: [ "80:80", "443:443" ]
        volumes:
            - "./sites-generated:/etc/nginx/conf.d:ro"
            - "/etc/letsencrypt:/etc/letsencrypt:ro"
            - "/etc/ssl:/etc/ssl:ro"

    nginx-gen:
        container_name: nginx-gen
        image: "jwilder/docker-gen:0.7.3"
        restart: unless-stopped
        command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/docker-gen/output/containers.conf"
        volumes:
            - "./templates:/etc/docker-gen/templates:ro"
            - "./sites-generated:/etc/docker-gen/output"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    mysql:
        container_name: mysql
        image: "mysql:8.0.0"
        restart: unless-stopped
        ports: [ "3306:3306" ]
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "/var/lib/mysql:/var/lib/mysql"
            - "/etc/mysql:/etc/mysql/conf.d"

    redis:
        container_name: redis
        image: "redis:3.2.6-alpine"
        restart: unless-stopped
        ports: [ "6379:6379" ]
        volumes:
            - "/var/lib/redis:/data"

    mail:
        extends:
            file: container-templates.yml
            service: mail
        container_name: mail
        hostname: mail.darsyn.io
        environment:
            PRIMARY_HOST: mail.darsyn.io

    neo4j:
        container_name: neo4j
        image: "neo4j:3.1.0"
        restart: unless-stopped
        ports: [ "7474:7474", "7687:7687" ]
        volumes:
            - "/var/lib/neo4j:/data"
