version: '2'
services:

    nginx:
        container_name: nginx
        image: "nginx:1.11.8-alpine"
        restart: unless-stopped
        ports: [ "80:80", "443:443" ]
        volumes:
            - "./sites-generated:/etc/nginx/conf.d:ro"
            - "/etc/letsencrypt:/etc/letsencrypt:ro"
            - "/etc/ssl:/etc/ssl:ro"
        depends_on: [ "docker-gen" ]
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"

    docker-gen:
        container_name: docker-gen
        image: "jwilder/docker-gen:0.7.3"
        restart: unless-stopped
        command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/reverse-proxy.conf /etc/docker-gen/output/containers.conf"
        volumes:
            - "./templates:/etc/docker-gen/templates:ro"
            - "./sites-generated:/etc/docker-gen/output"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"

    mysql:
        container_name: mysql
        image: "mysql:8.0.0"
        restart: unless-stopped
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "/var/lib/mysql:/var/lib/mysql"
            - "/etc/mysql:/etc/mysql/conf.d"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "1"

    redis:
        container_name: redis
        image: "redis:3.2.6-alpine"
        restart: unless-stopped
        ports: [ "6379:6379" ]
        volumes:
            - "/var/lib/redis:/data"
        logging:
            driver: "json-file"
            options:
                max-size: "25m"
                max-file: "1"

    mail:
        extends:
            file: container-templates.yml
            service: mail
        container_name: mail
        hostname: mail.darsyn.io
        environment:
            PRIMARY_HOST: mail.darsyn.io
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"

    neo4j:
        container_name: neo4j
        image: "neo4j:3.1.0"
        restart: unless-stopped
        volumes:
            - "/var/lib/neo4j:/data"
        logging:
            driver: "json-file"
            options:
                max-size: "25m"
                max-file: "1"

    cache:
        container_name: cache
        image: "alpine:3.5"
        command: date
        volumes:
            - "./.cache/composer:/root/.composer"
            - "./.cache/glide:/root/.glide"
            - "./.cache/npm:/root/.npm"
            - "./.cache/puli:/root/.puli"
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"
