version: '2'
services:

    mywebsite-php:
        extends:
            file: container-templates.yml
            service: php
        links: [ "mysql", "redis", "neo4j" ]
        volumes:
            - "./data/mywebsite:/srv"
    mywebsite-web:
        extends:
            file: container-templates.yml
            service: web
        hostname: "mywebsite.tld"
        links: [ "mywebsite-php:php" ]
        environment:
            VIRTUAL_HOST: "mywebsite.tld"
        volumes_from: [ "mywebsite-php" ]
        depends_on: [ "nginx" ]
    mywebsite-ssh:
        extends:
            file: container-templates.yml
            service: ssh
        hostname: "mywebsite.tld"
        links: [ "mysql", "redis", "neo4j" ]
        # Force a port here with "{hostPort}:22", or determine the port to
        # connect to once the container is created - either with
        # bin/ssh-config.sh or with the command:
        #    "docker port {containerName} 22"
        ports: [ 22 ]
        volumes_from: [ "mywebsite-php", "cache" ]
        volumes:
            - "./data/mywebsite.ssh:/root/.ssh:ro"
