version: '2'
services:

    mywebsite-php:
        extends:
            file: container-templates.yml
            service: php
        links: [ "mysql", "redis", "neo4j" ]
        volumes:
            - "./data/mywebsite:/srv"
    mywebsite-web:
        extends:
            file: container-templates.yml
            service: web
        hostname: "mywebsite.lo"
        links: [ "mywebsite-php:php" ]
        environment:
            VIRTUAL_HOST: "mywebsite.lo"
        volumes_from: [ "mywebsite-php" ]
        depends_on: [ "nginx" ]
    mywebsite-ssh:
        extends:
            file: container-templates.yml
            service: ssh
        hostname: "mywebsite.lo"
        links: [ "mysql", "redis", "neo4j" ]
        # Determine the port to connect to once the container is created with:
        # docker port {containerName} 22
        ports: [ 22 ]
        volumes_from: [ "mywebsite-php" ]
        volumes:
            - "./data/mywebsite.ssh:/root/.ssh:ro"
