# If you wish to use this template for a containerized GitLab installation then
# you can use `envsubst` command from the gettext package:

#   DOMAIN="mywebsite.tld" envsubst < docker-compose.override-example.com > ../docker-compose.override.yml

version: '2'
services:

    ${DOMAIN}-php:
        extends:
            file: container-templates.yml
            service: php
        links: [ "mysql", "redis", "neo4j" ]
        volumes:
            - "./data/${DOMAIN}:/srv"
    ${DOMAIN}-web:
        extends:
            file: container-templates.yml
            service: web
        hostname: "${DOMAIN}"
        links: [ "${DOMAIN}-php:php" ]
        environment:
            VIRTUAL_HOST: "${DOMAIN}"
        volumes_from: [ "${DOMAIN}-php" ]
        depends_on: [ "nginx" ]
    ${DOMAIN}-ssh:
        extends:
            file: container-templates.yml
            service: ssh
        hostname: "${DOMAIN}"
        links: [ "mysql", "redis", "neo4j" ]
        # Force a port here with "{hostPort}:22", or determine the port to
        # connect to once the container is created - either with
        # bin/ssh-config.sh or with the command:
        #    "docker-compose port ${DOMAIN}-ssh 22"
        ports: [ 22 ]
        volumes_from: [ "${DOMAIN}-php", "cache" ]
        volumes:
            - "./data/${DOMAIN}-ssh:/root/.ssh:ro"
